### ISSUE TITLE
Investigate removing getLegacyAngularInjector

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana-iot-twinmaker-app#199]
For Grafana 10.1.x with `angular_support_enabled = false` set in grafana, we need to remove all references to angular or the datasource won't be installed.
This includes our use of `getLegacyAngularInjector`.  We currently use this it to get the dashboard so that we can get, update, and refresh the current panels. We may be able to use the [scenes package](https://github.com/grafana/scenes) to do this instead. We should make sure the solution works with the version in hosted grafana. We currently have a [workaround](https://github.com/grafana/grafana/pull/67439) that's supporting it, but that will eventually go away.

**Comment by idastambuk** [comment]
I wrote down some thoughts after investigating this in [this doc](https://docs.google.com/document/d/1Ji3Y3qYUqStvEDrtuMStlrXB-QixX4LHm55adWIdq-A)
As far as I understand, the conclusion is that we will have to wait for the `dashboardSrv` to be exposed to external plugins, then start using it instead of the Angular injector. When I get a confirmation that this is happening, I will add it here (and create a ticket for this, since it will require updating the Grafana major versions in the plugin as well). 
But lmk if you have a better idea!

**Comment by idastambuk** [comment]
Closing as we're waiting for the Scenes library replace dashboards and expose dashboard apis here https://github.com/grafana/grafana/issues/73874
